#!/usr/bin/env bash

set -euo pipefail

shopt -s expand_aliases
source "$DOTFILES_PATH/shell/aliases.sh"
source "$DOTLY_PATH/scripts/core/_main.sh"

GREEN='\033[92m'
YELLOW='\033[0;33m'
NC='\033[0m' # No color

##? Take down all the docker containers up & running
##?
##? Usage:
##?    down
docs::parse "$@"

docker ps --format "table {{.ID}}\t{{.Names}}" | awk -v vGREEN="$GREEN" -v vNC="$NC" -v vYELLOW="$YELLOW" 'NR>1 { printf vNC"Stopping container "vGREEN $2 vNC"... "vYELLOW; system("docker stop -t5 " $1) }'
