#!/usr/bin/env bash

set -euo pipefail

shopt -s expand_aliases
source "$DOTFILES_PATH/shell/aliases.sh"
source "$DOTLY_PATH/scripts/core/_main.sh"

##? Take down all the docker containers up & running
##?
##? Usage:
##?    down
docs::parse "$@"

containers=$(docker ps | awk 'NR>1 { print $1 }')

for container in $containers; do
#  echo "Container up & running $container"
  docker stop $container
done
