#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Installs a terraform version using tfenv
##?
##? Usage:
##?    install <version>
docs::parse "$@"

tfenv install $version