#!/usr/bin/env bash

set -uo pipefail

shopt -s expand_aliases
source "$DOTFILES_PATH/shell/aliases.sh"
source "$DOTLY_PATH/scripts/core/_main.sh"

##? Login into AWS via SSO only if session is expired
##?
##? Usage:
##?    login
docs::parse "$@"

echo "Checking if SSO session has expired";
aws sts get-caller-identity &> /dev/null
EXIT_CODE="$?"  # $? is the exit code of the last statement

if [ $EXIT_CODE == 0 ]; then
    # auth is valid
    echo "Session still valid";
else
    # auth needs refresh
    echo "Session expired, logging in...";
    aws sso login
fi
