#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Installs the tfenv (a terraform versions manager tool)
##?
##? Usage:
##?    install
docs::parse "$@"

TFENV_HOME=$HOME/code/tfenv
LOCAL_BIN=$HOME/.local/bin

rm -rf $TFENV_HOME
git clone git@github.com:tfutils/tfenv.git $TFENV_HOME

files="$TFENV_HOME/bin/*"
for file in $files
do
  filename=$(basename -- "$file")
  echo "Processing $filename file..."
  rm -rf $LOCAL_BIN/$filename
  ln -s $TFENV_HOME/bin/$filename $LOCAL_BIN/$filename
done