#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Enable sending the sound from microphone to the output
##?
##? Usage:
##?    on
docs::parse "$@"

pactl load-module module-loopback latency_msec=1
