#!/usr/bin/env bash

set -euo pipefail

shopt -s expand_aliases

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Retrieves a secret with <name> in <bucket> and returns his value
##?
##? Usage:
##?    get <bucket> <name>
docs::parse "$@"

secret_value=$(exec encpass.sh show "$bucket" "$name")
#secret_value=$(exec pass show "$bucket/$name")

echo $secret_value
