#!/usr/bin/env bash

set -euo pipefail

shopt -s expand_aliases

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Saves a secret with <name> and <value> in <bucket>
##?
##? Usage:
##?    set <bucket> <name>
docs::parse "$@"

read -rsp "Enter your secret: " value

expect $DOTFILES_PATH/scripts/secrets/set_secret.exp "$bucket" "$name" "$value"
